Department/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Department.Models
{
    public class Employee
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [MaxLength(70)]
        public string Name { get; set; }
        [Required]
        [MaxLength(50)]
        public string Department { get; set; }
        [Required]
        [MaxLength(50)]
        public string Position { get; set; }
        public int? ChiefId { get; set; }
        public virtual Employee Chief { get; set; }
    }
}

Department/Models/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Department.Models
{
    public class EmployeeViewModel : Employee
    {
        public IEnumerable<Employee> Employees { get; set; }
    }
}

Department/Controllers/DepartmentController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Department.Models;
using System.Net;

namespace Department.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentRepository<Employee> db;

        public DepartmentController()
        {
            this.db = new DepartmentRepository();
        }

        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult EmployeesTable()
        {
            IEnumerable<Employee> EmployeesList = db.GetEmployeesList();
            return PartialView(EmployeesList);
        }


        [HttpGet]
        public ActionResult CreateEmployee()
        {
            EmployeeViewModel EVM = new EmployeeViewModel();
            EVM.Employees = db.GetEmployeesList();
            return PartialView(EVM);
        }


        [HttpPost]
        public ActionResult CreateEmployee([Bind(Include = "Id,Name,Position,Department,ChiefId")]Employee employee)
        {
            if (ModelState.IsValid)
            { 
                db.CreateEmployee(employee);
                db.Save();
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            EmployeeViewModel EVM = new EmployeeViewModel
            {
                Id = employee.Id,
                Name = employee.Name,
                Department = employee.Department,
                Position = employee.Position,
                ChiefId = employee.ChiefId,
                Chief = employee.Chief,
                Employees = db.GetEmployeesList()
            };
            return PartialView(EVM);
        }
         

        [HttpGet]
        public ActionResult EditEmployee(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }        
            var employee = db.GetEmployee(id.GetValueOrDefault());
            if (employee == null)
            {
                return HttpNotFound();
            }
            var employees = db.GetEmployeesList().Where(e => e.Id != id).ToList();
            EmployeeViewModel EVM = new EmployeeViewModel
            {
                Id = employee.Id,
                Name = employee.Name,
                Department = employee.Department,
                Position = employee.Position,
                ChiefId = employee.ChiefId,
                Chief = employee.Chief,
                Employees = employees
            };
            return PartialView(EVM);
        }


        [HttpPost]
        public ActionResult EditEmployee([Bind(Include = "Id,Name,Position,Department,ChiefId")]Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.UpdateEmployee(employee);
                db.Save();
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            employee.Chief = db.GetEmployee(employee.ChiefId.GetValueOrDefault());
            EmployeeViewModel EVM = new EmployeeViewModel
            {
                Id = employee.Id,
                Name = employee.Name,
                Department = employee.Department,
                Position = employee.Position,
                ChiefId = employee.ChiefId,
                Chief = employee.Chief,
                Employees = db.GetEmployeesList()
            };
            return PartialView(EVM);
        }


        [HttpGet]
        public ActionResult DeleteEmployee(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var employee = db.GetEmployee(id.GetValueOrDefault());
            if (employee == null)
            {
                return HttpNotFound();
            }
            return PartialView(employee);
        }


        [HttpPost]
        [ActionName("DeleteEmployee")]
        public ActionResult ConfirmDelete(int id)
        {
            var employees = db.GetEmployeesList();
            foreach (var e in employees)
            {
                if (id == e.ChiefId)
                {
                    e.ChiefId = null;
                }    
            }
            db.DeleteEmployee(id);
            db.Save();
            return Json(true, JsonRequestBehavior.AllowGet);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Department/Views/Department/CreateEmployee.cshtml
@model Department.Models.EmployeeViewModel


<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h3>Creating an employee</h3>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("CreateEmployee", "Department", FormMethod.Post, new { id = "createForm" }))
            {
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>    

                    <div class="form-group">
                        @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Chief, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select name="ChiefId" class="form-control">
                                <option value=""></option>
                                @foreach (var employee in Model.Employees)
                                {
                                    <option value="@employee.Id">@employee.Name</option>
                                }
                            </select>
                        </div>
                    </div>

                </div>
            }
            
            
        </div>
        <div class="modal-footer">
            <div class="col-md-12">
                <div class="form-actions no-color col-md-1 add-margin_bottom">
                    <input type="submit" value="Create" class="btn btn-info btn-lg" id="createSubmit" />
                </div>
                <div class="form-actions no-color col-md-offset-9 col-md-1 add-margin_bottom">
                    <input type="submit" value="Back" class="btn btn-info btn-lg cancelButton" />
                </div>
            </div>
        </div>
    </div>
</div>

Department/Views/Department/DeleteEmployee.cshtml
@model Department.Models.Employee


<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h3>Are you sure you want to delete this employee?</h3>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("DeleteEmployee", "Department", FormMethod.Post, new { id = "deleteForm" }))
            {
                <div>
                    <div class="col-md-offset-1 col-md-12">
                        <h3>Employee</h3>
                    </div>
                    <div>
                        <dl class="dl-horizontal">
                            @Html.HiddenFor(model => model.Id)
                            <dt>
                                @Html.DisplayNameFor(model => model.Name)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Name)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Department)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Department)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Position)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Position)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Chief)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Chief.Name)
                            </dd>
                        </dl>
                    </div>     
                </div>
            }
            <div class="modal-footer">
                <div class="col-md-12">
                    <div class="form-actions no-color col-md-1 add-margin_bottom">
                        <input type="submit" value="Delete" class="btn btn-info btn-lg" id="deleteSubmit" />
                    </div>
                    <div class="form-actions no-color col-md-offset-9 col-md-1 add-margin_bottom">
                        <input type="submit" value="Back" class="btn btn-info btn-lg cancelButton" />
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

Department/Views/Department/EditEmployee.cshtml
@model Department.Models.EmployeeViewModel


<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h3>Editing employee data</h3>
        </div>
        <div class="modal-body">
            @using (Html.BeginForm("EditEmployee", "Department", FormMethod.Post, new { id = "editForm" }))
            {
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Chief, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <select name="ChiefId" class="form-control">
                                @if (Model.ChiefId != null)
                                {
                                    <option selected="selected" value="@Model.ChiefId">@Model.Chief.Name</option>
                                } 
                                <option value=""></option>
                                @foreach (var employee in Model.Employees)
                                {
                                    <option value="@employee.Id">@employee.Name</option>
                                }
                            </select>
                        </div>
                    </div>

                </div>
            }


        </div>
        <div class="modal-footer">
            <div class="col-md-12">
                <div class="form-actions no-color col-md-1 add-margin_bottom">
                    <input type="submit" value="Edit" class="btn btn-info btn-lg" id="editSubmit" />
                </div>
                <div class="form-actions no-color col-md-offset-9 col-md-1 add-margin_bottom">
                    <input type="submit" value="Back" class="btn btn-info btn-lg cancelButton" />
                </div>
            </div>
        </div>
    </div>
</div>

Department/Views/Department/EmployeesTable.cshtml
@model IEnumerable<Department.Models.Employee>

@{
    Layout = null;
}

<table class="table">
    <tr>
        <th></th>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Position)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Chief)
        </th>
    </tr>

    @foreach (var item in Model)
    {

        <tr>
            <td>
                <a class="openModal" href="/Department/DeleteEmployee/@item.Id"><i class="fa fa-trash fa-lg" aria-hidden="true"></i></a>
            </td>
            <td>
                <a class="openModal" href="/Department/EditEmployee/@item.Id"><i class="fa fa-pencil-square-o fa-lg" aria-hidden="true"></i></a>
            </td>
            <td>
                @item.Name
            </td>
            <td>
                @item.Department
            </td>
            <td>
                @item.Position
            </td>
            <td>
                @(item.Chief != null ? item.Chief.Name : "")
            </td>

        </tr>
    }
</table>

Department/Views/Department/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Home Page";
}


<div class="col-sm-12 col-md-8">
    <div id="createBillButton" class="col-sm-offset-1 col-sm-11">
        @Html.ActionLink("CreateEmployee", "CreateEmployee", null, new { @class = "openModal btn btn-info btn btn-lg" })
    </div>
    <br />
    <div class="row">
        <div id="employeesTable">Loading...</div>
    </div>
</div>

<div class="modal-dialog"></div>

<div id="modDialog" class="modal fade"></div>


@section scripts
{
    <script type="text/javascript">

        $(function () {
            $.ajaxSetup({ cache: false });

            updateEmployeesTable();

            $(".container").on("click", ".cancelButton", function (e) {
                e.preventDefault();
                $('#modDialog').modal('hide');

            });


            $(".container").on("click", ".openModal", function (e) {
                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#modDialog').html(data);
                    $('#modDialog').modal('show');
                });
            });


            $(".container").on("click", "#createSubmit", function (e) {   
                e.preventDefault();
                $.ajax({
                    url: "@Url.Action("CreateEmployee", "Department")",
                    data: $('#createForm').serialize(),
                    type: "POST",
                    dataType: "text",
                    async: false,  
                    success: function (data) {
                        if (data == "true") {
                            $('#modDialog').modal('hide');
                            updateEmployeesTable();
                        } else {
                            $("#modDialog").html(data);
                        }
                    }
                });
            });


            $(".container").on("click", "#editSubmit", function (e) {   
                e.preventDefault();
                $.ajax({
                    url: "@Url.Action("EditEmployee", "Department")",
                    data: $('#editForm').serialize(),
                    type: "POST",
                    dataType: "text",
                    async: false,
                    success: function (data) {
                        if (data == "true") {
                            $('#modDialog').modal('hide');
                            updateEmployeesTable();
                        } else {
                            $("#modDialog").html(data);
                        }
                    }
                });
            });


            $(".container").on("click", "#deleteSubmit", function (e) {
                e.preventDefault();
                var form = $('#deleteForm');
                var data = { Id: $("[name='Id']", form).val() };
                $.ajax({
                    url: "@Url.Action("DeleteEmployee", "Department")",
                    data: JSON.stringify(data),
                    type: "POST",
                    contentType: "application/json;charset=utf-8",
                    dataType: "text",
                    success: function (data) {
                        if (data == "true") {
                            $('#modDialog').modal('hide');
                            updateEmployeesTable();
                        }
                    }
                });
            });


            function updateEmployeesTable() {
                $.ajax({
                    url: "@Url.Action("EmployeesTable", "Department")",
                    data: "",
                    type: "POST",
                    contentType: "application/json;charset=utf-8",
                    dataType: "text",
                    success: function (data) {
                        $("#employeesTable").html(data);
                    }
                });
            };

        });
    </script>
}